<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Faker\Factory as Faker;

/**
 * Dynamically generates generic test data for the entire application.
 * Creates predictable static accounts for testing, then utilizes Faker 
 * for randomized text, names, and emails for the bulk data. Uses a local
 * folder to pull random files to attach as document uploads.
 */
class GenericDataSeeder extends Seeder
{
    // --- SEEDING CONFIGURATION CONSTANTS ---
    private const PASSWORD = 'pass1234';
    
    // Test Accounts Setup
    private const NUM_TEST_CHAIRMEN = 1;
    private const NUM_TEST_INTERVIEWERS = 3;

    // Data Volume Config
    private const NUM_ORGANIZATIONS = 1;
    private const INTERVIEWERS_PER_ORG = 10;
    private const JOBS_PER_ORG = 6;
    private const MIN_APPS_PER_JOB = 10;
    private const MAX_APPS_PER_JOB = 20;
    private const INVITES_PER_ORG = 5;
    
    // Probabilities & Constraints
    private const INTERVIEW_PROBABILITY = 45; // % chance an application gets an interview
    private const MIN_INTERVIEWERS_PER_INTERVIEW = 1;
    private const MAX_INTERVIEWERS_PER_INTERVIEW = 3;
    private const FEEDBACK_PROBABILITY = 80; // % chance a completed interview has feedback notes submitted
    // ---------------------------------------

    private \Faker\Generator $faker;
    private array $seedFiles = []; 

    private array $staticChairmenIds = [];
    private array $staticInterviewerIds = [];
    private array $staticAccountEmails = [];

    public function run(): void
    {
        $this->faker = Faker::create();

        $this->cleanDatabase();
        $this->prepareSeedFiles();
        $this->createStaticTestAccounts();

        for ($orgIndex = 1; $orgIndex <= self::NUM_ORGANIZATIONS; $orgIndex++) {
            $this->seedOrganizationData($orgIndex);
        }
        
        $this->printSummary();
    }

    private function cleanDatabase(): void
    {
        $this->command->info('Cleaning database tables and document storage...');

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('organization_invites')->truncate();
        DB::table('organization_user_permissions')->truncate();
        DB::table('organization_user')->truncate();
        DB::table('interview_user')->truncate();
        DB::table('interviews')->truncate();
        DB::table('application_answers')->truncate();
        DB::table('documents')->truncate();
        DB::table('applications')->truncate();
        DB::table('job_positions')->truncate();
        DB::table('template_fields')->truncate();
        DB::table('application_templates')->truncate();
        DB::table('organizations')->truncate();
        DB::table('users')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        Storage::disk('local')->deleteDirectory('documents');
    }

    private function prepareSeedFiles(): void
    {
        $seedDocsDir = 'seed_documents';

        if (!Storage::disk('local')->exists($seedDocsDir)) {
            Storage::disk('local')->makeDirectory($seedDocsDir);
        }

        // Minimal valid dummy files so browser viewers don't crash
        $dummyFiles = [
            'dummy_resume.pdf' => "%PDF-1.4\n%âãÏÓ\n1 0 obj\n<</Type/Catalog/Pages 2 0 R>>\nendobj\n2 0 obj\n<</Type/Pages/Count 1/Kids[3 0 R]>>\nendobj\n3 0 obj\n<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Resources<<>>/Contents 4 0 R>>\nendobj\n4 0 obj\n<</Length 21>>\nstream\nBT /F1 24 Tf 100 700 Td (Dummy PDF) Tj ET\nendstream\nendobj\nxref\n0 5\n0000000000 65535 f\n0000000015 00000 n\n0000000060 00000 n\n0000000117 00000 n\n0000000222 00000 n\ntrailer\n<</Size 5/Root 1 0 R>>\nstartxref\n294\n%%EOF",
            'dummy_image.png' => base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
            'dummy_portfolio.txt' => "This is a generic dummy text file generated by the seeder."
        ];

        // Safely put the files using the Storage engine
        foreach ($dummyFiles as $filename => $content) {
            $path = "{$seedDocsDir}/{$filename}";
            if (!Storage::disk('local')->exists($path)) {
                Storage::disk('local')->put($path, $content);
            }
        }

        // Force OS permissions so the web server can read them later
        try {
            @chmod(Storage::disk('local')->path($seedDocsDir), 0755);
            foreach (Storage::disk('local')->files($seedDocsDir) as $file) {
                @chmod(Storage::disk('local')->path($file), 0644);
            }
        } catch (\Throwable $e) {
            // Ignore if OS does not support chmod (e.g., Windows)
        }

        $this->seedFiles = Storage::disk('local')->files($seedDocsDir);

        if (empty($this->seedFiles)) {
            $this->command->error("Failed to prepare seed files. Ensure storage permissions are correct.");
        }
    }

    private function createStaticTestAccounts(): void
    {
        for ($i = 1; $i <= self::NUM_TEST_CHAIRMEN; $i++) {
            $email = "chairman{$i}@example.com";
            $this->staticChairmenIds[] = $this->createUser("Test Chairman {$i}", 'chairman', $email);
            $this->staticAccountEmails['chairman'][] = $email;
        }

        for ($i = 1; $i <= self::NUM_TEST_INTERVIEWERS; $i++) {
            $email = "interviewer{$i}@example.com";
            $this->staticInterviewerIds[] = $this->createUser("Test Interviewer {$i}", 'interviewer', $email);
            $this->staticAccountEmails['interviewer'][] = $email;
        }
    }

    private function seedOrganizationData(int $orgIndex): void
    {
        if ($orgIndex <= count($this->staticChairmenIds)) {
            $chairmanId = $this->staticChairmenIds[$orgIndex - 1];
        } else {
            $chairmanId = $this->createUser("Chairman Org {$orgIndex}", 'chairman', "chairman{$orgIndex}@example.com");
        }

        $orgId = DB::table('organizations')->insertGetId([
            'chairman_id' => $chairmanId,
            'name' => $this->faker->company() . ' Hiring',
            'join_code' => strtoupper($this->faker->lexify('????')) . $orgIndex . '2026',
            'created_at' => now()->subDays(rand(60, 180)),
            'updated_at' => now(),
        ]);

        $this->attachUserToOrganization($orgId, $chairmanId);
        $interviewerIds = [];

        if ($orgIndex === 1) {
            foreach ($this->staticInterviewerIds as $staticIntId) {
                $this->attachUserToOrganization($orgId, $staticIntId);
                $this->assignRandomPermissions($orgId, $staticIntId, $chairmanId, true);
                $interviewerIds[] = $staticIntId;
            }
        }

        for ($i = 1; $i <= self::INTERVIEWERS_PER_ORG; $i++) {
            $userId = $this->createUser(
                $this->faker->name(), 
                'interviewer', 
                "org{$orgIndex}_interviewer{$i}@example.com"
            );
            $this->attachUserToOrganization($orgId, $userId);
            $this->assignRandomPermissions($orgId, $userId, $chairmanId);
            $interviewerIds[] = $userId;
        }

        $templateIds = $this->seedTemplates($orgId, $chairmanId);

        for ($j = 0; $j < self::JOBS_PER_ORG; $j++) {
            $jobId = $this->seedJobPosition($orgId, $templateIds[array_rand($templateIds)], $chairmanId);
            
            $numApps = rand(self::MIN_APPS_PER_JOB, self::MAX_APPS_PER_JOB);
            for ($a = 0; $a < $numApps; $a++) {
                $appId = $this->seedApplication($jobId, $templateIds[array_rand($templateIds)]);
                $this->seedInterviews($appId, $interviewerIds);
            }
        }

        $this->seedInvites($orgId, $chairmanId);
    }

    private function createUser(string $name, string $role, string $email): int
    {
        return DB::table('users')->insertGetId([
            'name' => $name,
            'role' => $role,
            'email' => $email,
            'email_verified_at' => now(),
            'password' => Hash::make(self::PASSWORD),
            'remember_token' => Str::random(10),
            'created_at' => now()->subDays(rand(10, 100)),
            'updated_at' => now(),
        ]);
    }

    private function attachUserToOrganization(int $organizationId, int $userId): void
    {
        DB::table('organization_user')->insert([
            'organization_id' => $organizationId,
            'user_id' => $userId,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function assignRandomPermissions(int $orgId, int $userId, int $grantedBy, bool $grantAll = false): void
    {
        $permissionIds = DB::table('permissions')->pluck('id')->toArray();
        
        if ($grantAll) {
            $selectedPerms = $permissionIds;
        } else {
            shuffle($permissionIds);
            $numPerms = rand(1, count($permissionIds));
            $selectedPerms = array_slice($permissionIds, 0, $numPerms);
        }

        $rows = [];
        foreach ($selectedPerms as $permId) {
            $rows[] = [
                'organization_id' => $orgId,
                'user_id' => $userId,
                'permission_id' => $permId,
                'granted_by' => $grantedBy,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('organization_user_permissions')->insert($rows);
    }

    private function seedTemplates(int $orgId, int $creatorId): array
    {
        $templates = [
            'General Application' => [
                ['label' => 'Why do you want this role?', 'type' => 'textarea', 'required' => true],
                ['label' => 'Expected Salary', 'type' => 'text', 'required' => false],
                ['label' => 'Upload Resume', 'type' => 'file', 'required' => true],
            ],
            'Technical Role Application' => [
                ['label' => 'GitHub Profile URL', 'type' => 'text', 'required' => true],
                ['label' => 'Primary Programming Language', 'type' => 'select', 'options' => json_encode(['PHP', 'Python', 'Java', 'JavaScript', 'C++']), 'required' => true],
                ['label' => 'Upload Resume', 'type' => 'file', 'required' => true],
                ['label' => 'Code Sample (PDF)', 'type' => 'file', 'required' => false],
            ]
        ];

        $templateIds = [];

        foreach ($templates as $name => $fields) {
            $templateId = DB::table('application_templates')->insertGetId([
                'organization_id' => $orgId,
                'created_by' => $creatorId,
                'name' => $name,
                'request_name' => true,
                'request_email' => true,
                'request_phone' => $this->faker->boolean(),
                'created_at' => now()->subDays(rand(30, 90)),
                'updated_at' => now(),
            ]);

            $order = 1;
            foreach ($fields as $field) {
                DB::table('template_fields')->insert([
                    'template_id' => $templateId,
                    'label' => $field['label'],
                    'type' => $field['type'],
                    'options' => $field['options'] ?? null,
                    'required' => $field['required'],
                    'file_multiple' => false,
                    'char_max' => $field['type'] === 'textarea' ? 1000 : 255,
                    'order' => $order++,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
            
            $templateIds[] = $templateId;
        }

        return $templateIds;
    }

    private function seedJobPosition(int $orgId, int $templateId, int $creatorId): int
    {
        $statuses = ['open', 'open', 'open', 'closed'];

        return DB::table('job_positions')->insertGetId([
            'organization_id' => $orgId,
            'template_id' => $templateId,
            'created_by' => $creatorId,
            'title' => $this->faker->jobTitle(),
            'description' => $this->faker->paragraphs(3, true),
            'requirements' => "• " . implode("\n• ", $this->faker->sentences(4)),
            'status' => $statuses[array_rand($statuses)],
            'created_at' => now()->subDays(rand(10, 60)),
            'updated_at' => now(),
        ]);
    }

    private function seedApplication(int $jobId, int $templateId): int
    {
        $statuses = ['submitted', 'under_review', 'under_review', 'no_longer_under_consideration', 'withdrawn'];
        $appDate = now()->subDays(rand(1, 30));

        $appId = DB::table('applications')->insertGetId([
            'job_position_id' => $jobId,
            'template_id' => $templateId,
            'applicant_name' => $this->faker->name(),
            'applicant_email' => $this->faker->unique()->safeEmail(),
            'applicant_phone' => $this->faker->phoneNumber(),
            'status' => $statuses[array_rand($statuses)],
            'created_at' => $appDate,
            'updated_at' => $appDate,
        ]);

        $fields = DB::table('template_fields')->where('template_id', $templateId)->get();

        foreach ($fields as $field) {
            $value = null;
            $documentId = null;

            if ($field->type === 'text') {
                $value = $this->faker->sentence();
            } elseif ($field->type === 'textarea') {
                $value = $this->faker->paragraph();
            } elseif ($field->type === 'select' || $field->type === 'radio') {
                $opts = json_decode($field->options, true);
                if (!empty($opts)) {
                    $value = $opts[array_rand($opts)];
                }
            } elseif ($field->type === 'file') {
                $documentId = $this->createRandomDocument($appId);
                $value = DB::table('documents')->where('id', $documentId)->value('filename');
            }

            DB::table('application_answers')->insert([
                'application_id' => $appId,
                'template_field_id' => $field->id,
                'value' => $value,
                'document_id' => $documentId,
                'created_at' => $appDate,
                'updated_at' => $appDate,
            ]);
        }

        return $appId;
    }

    private function createRandomDocument(int $applicationId): int
    {
        // Select a random file from our seed folder array
        $sourceFile = $this->seedFiles[array_rand($this->seedFiles)];
        $originalName = basename($sourceFile);
        $extension = pathinfo($sourceFile, PATHINFO_EXTENSION);
        
        $mimes = [
            'pdf' => 'application/pdf',
            'doc' => 'application/msword',
            'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'txt' => 'text/plain',
            'jpg' => 'image/jpeg',
            'png' => 'image/png',
        ];
        $mimetype = $mimes[strtolower($extension)] ?? 'application/octet-stream';

        $storedFilename = uniqid() . '_' . $originalName;
        $relativePath = "documents/{$applicationId}/{$storedFilename}";
        $dirPath = "documents/{$applicationId}";

        // Use Storage engine to copy (automatically creates target subdirectories)
        Storage::disk('local')->copy($sourceFile, $relativePath);

        // Force OS permissions so the web server can fetch it over HTTP
        try {
            @chmod(Storage::disk('local')->path('documents'), 0755);
            @chmod(Storage::disk('local')->path($dirPath), 0755);
            @chmod(Storage::disk('local')->path($relativePath), 0644);
        } catch (\Throwable $e) {
            // Ignore if OS does not support chmod (e.g., Windows)
        }

        return DB::table('documents')->insertGetId([
            'application_id' => $applicationId,
            'filename' => $originalName,
            'filepath' => $relativePath,
            'mimetype' => $mimetype,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function seedInterviews(int $appId, array $interviewerIds): void
    {
        if (rand(1, 100) > self::INTERVIEW_PROBABILITY) {
            return;
        }

        $statusOptions = ['scheduled', 'completed', 'completed', 'canceled'];
        $status = $statusOptions[array_rand($statusOptions)];
        
        $scheduledAt = $status === 'scheduled' 
            ? now()->addDays(rand(1, 14))->setTime(rand(9, 16), 0)
            : now()->subDays(rand(1, 14))->setTime(rand(9, 16), 0);

        $interviewId = DB::table('interviews')->insertGetId([
            'application_id' => $appId,
            'scheduled_at' => $scheduledAt,
            'status' => $status,
            'created_at' => now()->subDays(rand(15, 30)),
            'updated_at' => now(),
        ]);

        shuffle($interviewerIds);
        $assignedInterviewers = array_slice($interviewerIds, 0, rand(self::MIN_INTERVIEWERS_PER_INTERVIEW, self::MAX_INTERVIEWERS_PER_INTERVIEW));

        foreach ($assignedInterviewers as $userId) {
            $notes = null;
            $feedbackAt = null;

            if ($status === 'completed' && rand(1, 100) <= self::FEEDBACK_PROBABILITY) {
                $notes = $this->faker->paragraph();
                $feedbackAt = $scheduledAt->copy()->addHours(rand(1, 24));
            }

            DB::table('interview_user')->insert([
                'interview_id' => $interviewId,
                'user_id' => $userId,
                'notes' => $notes,
                'feedback_submitted_at' => $feedbackAt,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function seedInvites(int $orgId, int $creatorId): void
    {
        for ($i = 0; $i < self::INVITES_PER_ORG; $i++) {
            DB::table('organization_invites')->insert([
                'organization_id' => $orgId,
                'created_by' => $creatorId,
                'code' => strtoupper(Str::random(8)),
                'email' => $this->faker->boolean(50) ? $this->faker->safeEmail() : null,
                'used' => $this->faker->boolean(30),
                'created_at' => now()->subDays(rand(1, 10)),
                'updated_at' => now(),
            ]);
        }
    }

    private function printSummary(): void
    {
        $this->command->info("\n✅ Generic test data seeded successfully.\n");
        $this->command->warn("==================================================");
        $this->command->warn("              TEST ACCOUNTS CREATED               ");
        $this->command->warn("==================================================");
        $this->command->warn("Password for ALL test accounts: " . self::PASSWORD);
        $this->command->warn("--------------------------------------------------");
        
        $this->command->info("CHAIRMEN:");
        foreach ($this->staticAccountEmails['chairman'] as $index => $email) {
            $orgNum = $index + 1;
            $this->command->line("  - {$email} (Assigned to Org {$orgNum})");
        }
        
        $this->command->line("");
        $this->command->info("INTERVIEWERS (All active in Org 1):");
        foreach ($this->staticAccountEmails['interviewer'] as $email) {
            $this->command->line("  - {$email}");
        }
        $this->command->warn("==================================================\n");
    }
}