CREATE DATABASE IF NOT EXISTS `laravel`;
GRANT ALL PRIVILEGES ON `laravel`.* TO 'laravel'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS laravel_testing;
GRANT ALL PRIVILEGES ON laravel_testing.* TO 'laravel'@'%';
FLUSH PRIVILEGES;